/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CuidadosRouteImport } from './routes/cuidados'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadosRoute = CuidadosRouteImport.update({
  id: '/cuidados',
  path: '/cuidados',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/cuidados': typeof CuidadosRoute
  '/guia': typeof GuiaRoute
  '/loja': typeof LojaRoute
  '/pedido': typeof PedidoRoute
  '/sobre': typeof SobreRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/cuidados': typeof CuidadosRoute
  '/guia': typeof GuiaRoute
  '/loja': typeof LojaRoute
  '/pedido': typeof PedidoRoute
  '/sobre': typeof SobreRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/cuidados': typeof CuidadosRoute
  '/guia': typeof GuiaRoute
  '/loja': typeof LojaRoute
  '/pedido': typeof PedidoRoute
  '/sobre': typeof SobreRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/cuidados'
    | '/guia'
    | '/loja'
    | '/pedido'
    | '/sobre'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/cuidados'
    | '/guia'
    | '/loja'
    | '/pedido'
    | '/sobre'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/cuidados'
    | '/guia'
    | '/loja'
    | '/pedido'
    | '/sobre'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  CuidadosRoute: typeof CuidadosRoute
  GuiaRoute: typeof GuiaRoute
  LojaRoute: typeof LojaRoute
  PedidoRoute: typeof PedidoRoute
  SobreRoute: typeof SobreRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidados': {
      id: '/cuidados'
      path: '/cuidados'
      fullPath: '/cuidados'
      preLoaderRoute: typeof CuidadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  CuidadosRoute: CuidadosRoute,
  GuiaRoute: GuiaRoute,
  LojaRoute: LojaRoute,
  PedidoRoute: PedidoRoute,
  SobreRoute: SobreRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
