/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CuidadosRouteImport } from './routes/cuidados'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContaRecuperarRouteImport } from './routes/conta.recuperar'
import { Route as ContaRedefinirRouteImport } from './routes/conta.redefinir'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'
import { Route as ApiWebhooksRastreioRouteImport } from './routes/api/webhooks/rastreio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadosRoute = CuidadosRouteImport.update({
  id: '/cuidados',
  path: '/cuidados',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRecuperarRoute = ContaRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => ContaRoute,
} as any)
const ContaRedefinirRoute = ContaRedefinirRouteImport.update({
  id: '/redefinir',
  path: '/redefinir',
  getParentRoute: () => ContaRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRastreioRoute = ApiWebhooksRastreioRouteImport.update({
  id: '/api/webhooks/rastreio',
  path: '/api/webhooks/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/compras': typeof ComprasRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cuidados': typeof CuidadosRoute
  '/guia': typeof GuiaRoute
  '/loja': typeof LojaRoute
  '/pedido': typeof PedidoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/conta/recuperar': typeof ContaRecuperarRoute
  '/conta/redefinir': typeof ContaRedefinirRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/webhooks/rastreio': typeof ApiWebhooksRastreioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/compras': typeof ComprasRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cuidados': typeof CuidadosRoute
  '/guia': typeof GuiaRoute
  '/loja': typeof LojaRoute
  '/pedido': typeof PedidoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/conta/recuperar': typeof ContaRecuperarRoute
  '/conta/redefinir': typeof ContaRedefinirRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/webhooks/rastreio': typeof ApiWebhooksRastreioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/compras': typeof ComprasRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cuidados': typeof CuidadosRoute
  '/guia': typeof GuiaRoute
  '/loja': typeof LojaRoute
  '/pedido': typeof PedidoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/conta/recuperar': typeof ContaRecuperarRoute
  '/conta/redefinir': typeof ContaRedefinirRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/webhooks/rastreio': typeof ApiWebhooksRastreioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/checkout'
    | '/compras'
    | '/conta'
    | '/contato'
    | '/cuidados'
    | '/guia'
    | '/loja'
    | '/pedido'
    | '/privacidade'
    | '/sobre'
    | '/conta/recuperar'
    | '/conta/redefinir'
    | '/produto/$slug'
    | '/api/webhooks/mercadopago'
    | '/api/webhooks/rastreio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/checkout'
    | '/compras'
    | '/conta'
    | '/contato'
    | '/cuidados'
    | '/guia'
    | '/loja'
    | '/pedido'
    | '/privacidade'
    | '/sobre'
    | '/conta/recuperar'
    | '/conta/redefinir'
    | '/produto/$slug'
    | '/api/webhooks/mercadopago'
    | '/api/webhooks/rastreio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/checkout'
    | '/compras'
    | '/conta'
    | '/contato'
    | '/cuidados'
    | '/guia'
    | '/loja'
    | '/pedido'
    | '/privacidade'
    | '/sobre'
    | '/conta/recuperar'
    | '/conta/redefinir'
    | '/produto/$slug'
    | '/api/webhooks/mercadopago'
    | '/api/webhooks/rastreio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  CheckoutRoute: typeof CheckoutRoute
  ComprasRoute: typeof ComprasRoute
  ContaRoute: typeof ContaRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CuidadosRoute: typeof CuidadosRoute
  GuiaRoute: typeof GuiaRoute
  LojaRoute: typeof LojaRoute
  PedidoRoute: typeof PedidoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
  ApiWebhooksRastreioRoute: typeof ApiWebhooksRastreioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidados': {
      id: '/cuidados'
      path: '/cuidados'
      fullPath: '/cuidados'
      preLoaderRoute: typeof CuidadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/recuperar': {
      id: '/conta/recuperar'
      path: '/recuperar'
      fullPath: '/conta/recuperar'
      preLoaderRoute: typeof ContaRecuperarRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/redefinir': {
      id: '/conta/redefinir'
      path: '/redefinir'
      fullPath: '/conta/redefinir'
      preLoaderRoute: typeof ContaRedefinirRouteImport
      parentRoute: typeof ContaRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/rastreio': {
      id: '/api/webhooks/rastreio'
      path: '/api/webhooks/rastreio'
      fullPath: '/api/webhooks/rastreio'
      preLoaderRoute: typeof ApiWebhooksRastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContaRouteChildren {
  ContaRecuperarRoute: typeof ContaRecuperarRoute
  ContaRedefinirRoute: typeof ContaRedefinirRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaRecuperarRoute: ContaRecuperarRoute,
  ContaRedefinirRoute: ContaRedefinirRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  CheckoutRoute: CheckoutRoute,
  ComprasRoute: ComprasRoute,
  ContaRoute: ContaRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CuidadosRoute: CuidadosRoute,
  GuiaRoute: GuiaRoute,
  LojaRoute: LojaRoute,
  PedidoRoute: PedidoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
  ApiWebhooksRastreioRoute: ApiWebhooksRastreioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
